import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "../components/ui/sonner";
import Navbar from "@/components/layout/Navbar";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-siderbar";
//import { AppSiderbar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ ["--navbar-height"]: "3rem" } as React.CSSProperties}
      >
        <AuthProvider>
          <Navbar />
          <SidebarProvider  className="bg-[#EFE9D5] border border-b-black"  defaultOpen={true}>
            <AppSidebar  />
                <div className="p-2 bg-[#EFE9D5]">
    <SidebarTrigger />
  </div>
              <SidebarInset className="pt-(--navbar-height)  flex-1 overflow-auto">
                {children}
              </SidebarInset>
            <Toaster />
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
